name: "setup-dependencies"
description: "setup-dependencies"

inputs:
  install-node:
    description: "Should node be installed"
    required: false
  install-go:
    description: "Should go be installed"
    required: false
  install-python:
    description: "Should python be installed"
    required: false
  install-task:
    description: "Should task be installed"
    required: false

runs:
  using: 'composite'
  steps:
    - name: setup-task
      if: ${{inputs.install-task}} == true
      shell: bash
      run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/task/task/setup.deb.sh' | sudo -E bash
          sudo apt update
          sudo apt install -y task
          task --version
          
    - name: setup-node
      if: ${{inputs.install-node}} == true
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: setup-python
      if: ${{inputs.install-python}} == true
      uses: actions/setup-node@v6
      with:
        node-version: 24
    
